---
name: VersionCheck container implementation

description: Run tool-version-check in its published container

inputs:
  source:
    required: true
  package:
    required: true
  current-version:
    required: true
  version-pattern:
    required: false
  include-prereleases:
    required: true
  channels:
    required: false
  subdirs:
    required: false
  github-token:
    required: false

runs:
  using: composite
  steps:
    - name: Run VersionCheck
      id: versioncheck
      uses: docker://ghcr.io/theboutroslab/versioncheck:DOCKER_IMAGE_TAG
      env:
        VERSIONCHECK_SOURCE: ${{ inputs.source }}
        VERSIONCHECK_PACKAGE: ${{ inputs.package }}
        VERSIONCHECK_CURRENT_VERSION: ${{ inputs.current-version }}
        VERSIONCHECK_VERSION_PATTERN: ${{ inputs.version-pattern }}
        VERSIONCHECK_INCLUDE_PRERELEASES: ${{ inputs.include-prereleases }}
        VERSIONCHECK_CHANNELS: ${{ inputs.channels }}
        VERSIONCHECK_SUBDIRS: ${{ inputs.subdirs }}
        VERSIONCHECK_RESULT_PATH: /github/workspace/.git/versioncheck-result.json
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        entrypoint: /bin/bash
        args: /github/workspace/.git/run-versioncheck.sh
